# Generated by Django 3.2 on 2021-04-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='data_emprestimo',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='pessoa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoas'),
        ),
    ]
