# Generated by Django 3.2 on 2021-04-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tema', models.CharField(max_length=10)),
                ('emprestado', models.BooleanField(default=False)),
                ('pessoas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoas')),
            ],
        ),
    ]
