# Generated by Django 3.2 on 2021-04-13 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='pessoas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoas'),
        ),
    ]
