# Generated by Django 3.2 on 2021-04-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livros_pessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='tema',
            field=models.CharField(max_length=20),
        ),
    ]
