# Generated by Django 3.2 on 2021-04-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispensa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispensa',
            options={},
        ),
    ]
