# Generated by Django 3.2 on 2021-04-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispensa', '0004_dispensa_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensa',
            name='pessoa',
        ),
    ]
