# Generated by Django 3.2 on 2021-05-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_remedio', models.CharField(max_length=50)),
                ('data_validade', models.DateField()),
                ('medico', models.CharField(max_length=50)),
                ('motivo_remedio', models.TextField()),
            ],
        ),
    ]
